const express=require("express")
const app=express()
const dotenv=require("dotenv")
dotenv.config()
require("./conn/conn")
const cors=require("cors")
const signup=require("./routes/user")
const books=require("./routes/books")
const favourites=require("./routes/favourate")
const cart=require("./routes/cart")
const order=require("./routes/orders")
app.use(cors())
app.use(express.json());
app.use("/api/auth",signup)
app.use("/api/auth",books)
app.use("/api/auth",favourites)
app.use("/api/auth",cart)
app.use("/api/auth",order)
app.get("/",(req,res)=>{
    res.send("server created")
})
app.listen(process.env.PORT, (req, res) => {
    console.log(`server connected ${process.env.PORT}`)
})
